name: baryonic-backend-task
services:
  stock_generator:
    container_name: generator
    build:
      context: ./generator
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6371:6379"

  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=stocks
      - SHARED_BUFFERS=512MB 
      - EFFECTIVE_CACHE_SIZE=1GB
      - MAINTENANCE_WORK_MEM=128MB
      - WAL_BUFFERS=64MB
      - LISTEN_ADDRESSES=* # Required for Grafana and other containers to reach PostgreSQL.
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresql.conf.template:/etc/postgresql/postgresql.conf.template:ro
    expose:
      - "5432"
    command: >
      sh -c "envsubst < /etc/postgresql/postgresql.conf.template > /tmp/postgresql.conf &&
            docker-entrypoint.sh postgres -c config_file=/tmp/postgresql.conf"

  subscriber:
    container_name: subscriber
    build:
      context: ./subscriber
      dockerfile: Dockerfile
    depends_on:
      - redis
      - postgres
      - centrifugo
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=stocks
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - CENTRIFUGO_API_URL=http://centrifugo:8000/api
      - CENTRIFUGO_API_KEY=centrifugo-api-key
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=stocks
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    expose:
     - "5050" 

  centrifugo:
    container_name: centrifugo
    image: centrifugo/centrifugo
    volumes:
      - ./centrifugo:/centrifugo
    command: centrifugo -c /centrifugo/config.json
    expose: 
      - "8000"

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./client:/usr/share/nginx/html:ro 
    depends_on:
      - backend
      - centrifugo
      - grafana

  vector:
    image: timberio/vector:0.48.0-alpine
    container_name: vector
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./vector/vector.yaml:/etc/vector/vector.yaml:ro
    depends_on:
      - subscriber
      - postgres
    command: ["-c", "/etc/vector/vector.yaml"]

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - postgres
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_ROOT_URL=http://localhost/grafana/
    volumes:
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    expose:
      - "3000"


